### ISSUE TITLE
Suggestion: Meteorite Dimension Only Mining Dim.

### ISSUE THREAD

**Issue by StoneLegion** [AllTheMods/Remix#13]
I recommend that the Meteorite's only spawn in the Mining Dimension. They can really make a world quite ugly fast. Even more so with normal sized BoP you might finally come across that one nice looking biome and boom it looks really bad.

They also tend to spawn in the Lost City and make things look quite ugly in a none nice way. 

This also happens if you select Lost City BoP World Gen and honestly if we have the Mining Dim let's just send these ugly guys to that Dim as well!

**Comment by StoneLegion** [comment]
Current Settings For the Lazy :)

```
worldgen {
    D:meteoriteClusterChance=0.1
    I:meteoriteDimensionWhitelist <
        0
        -6
     >
    I:meteoriteMaximumSpawnHeight=180
    I:minMeteoriteDistance=707
    I:quartzOresClusterAmount=15
    I:quartzOresPerCluster=4
    D:spawnChargedChance=0.07999998331069946
}
```

**Comment by StoneLegion** [comment]
Added note: Maybe add a tooltip if this change is put into effect for Skystone that it can be found in the Mining Dimension.

**Comment by Syer10** [comment]
Wrong repo. All The Mods 3 Remix repo is here: https://github.com/AllTheMods/ATM3-Remix

**Comment by FallenEagle1** [comment]
Im taking care of it

**Comment by FallenEagle1** [comment]
Moved over to ATM3 Remix repo.
