### ISSUE TITLE
Suggestion: Signals Mod Added.

### ISSUE THREAD

**Issue by StoneLegion** [AllTheMods/Remix#14]
It adds Factorio / OpenTTD Style Signals.
https://minecraft.curseforge.com/projects/signals

**Why Add it?:**
- Automated Rail Systems.
- Adds a lot of depth without other players being forced to use it as it's optional.
- No Railcraft, and other mods that offer such a system in the pack.
- Lost World seems like a really fun themed World to start with and would be perfect as it spawns an entire subway system to making more use / enjoyment with such a mod.

The mod can be added or removed without adding too much issues / problems and no world gen required.

**Comment by FallenEagle1** [comment]
Moved over to ATM3-Remix repo
