### ISSUE TITLE
Suggestion: Lost Souls are too frequent.

### ISSUE THREAD

**Issue by StoneLegion** [AllTheMods/Remix#15]
Via: lostsouls.cfg

```
    # The chance that a building is haunted [range: 0.0 ~ 1.0, default: 0.8]
    S:hauntedChance=0.8
```

Right now the chance to be haunted is 80%. So this means if you went into 100 buildings 80 of them be haunted. I think maybe a 10% chance or even less seems more appropriate. Not sure if it's suppose to be a fun thing to run in and then you clear it or rather a painful experience where no one wants to go into any building. 

If you want the value to be slightly higher I recommend Lowering the Max amount of mobs needed to kill as right now it's max of 50.
```
    # The maximum amount of mobs that are spawned by a haunted building [range: 1 ~ 10000, default: 50]
    I:maxMobs=50
```
Minimal mobs is 10 not too bad as long your not hitting these none stop.
```
    # The minimum amount of mobs that are spawned by a haunted building [range: 1 ~ 10000, default: 10]
    I:minMobs=10
```

Keep in Mind these hit the Entire Chunk the Buildings are in. Meaning that when your mining sadly you will find chests but also get the messages, etc. Becomes a bit tiresome at such a high rate.

**Comment by FallenEagle1** [comment]
Moved over to ATM3 Remix repo
